# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.4
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - run: sudo apt-get install software-properties-common
      - run: sudo add-apt-repository ppa:linuxuprising/libpng12 && sudo apt update
      - run: sudo apt-get install -y libpng12-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - checkout
      - run: php wm.php
      
